### PR TITLE
Merging appstudio-shared API

### PR DESCRIPTION
**Pull request by drpaneas**
See the JIRA ticket: https://issues.redhat.com/browse/GITOPSRVCE-236

For the reviewer:

- Please let me know what needs to be removed/added into the `config/rbac` directory as I couldn't find how these are getting generated.

### CODE REVIEW

**Comment by drpaneas** [comment]
Changelog for promotion_types.go

Changes:

* `ApplicationPromotionRun` struct rename --> `PromotionRun` (required a change in `PromotionRunList` as well as it's using it)
* `ApplicationPromotionRunList` struct rename --> `PromotionRunList`
* `ApplicationPromotionRunSpec` struct rename --> `PromotionRunSpec` (required a change to `PromotionRun` as well as it used this)
* `ApplicationPromotionRunStatus` rename --> `PromotionRunStatus` (required a change to `PromotionRun` as well as it used this)
    * Also adds two member fields: `PromotionStartTime` and `Conditions` (including the `PromotionRunCondition` new type)
* Rename 3 `consts`: `ApplicationPromotionRunEnvironmentStatus_Success` --> `PromotionRunEnvironmentStatus_Success`
                     `ApplicationPromotionRunEnvironmentStatus_InProgress` --> `PromotionRunEnvironmentStatus_InProgress`
                     `ApplicationPromotionRunEnvironmentStatus_Failed` --> `PromotionRunEnvironmentStatus_Failed`
* Init function `SchemeBuilder.Register(&ApplicationPromotionRun{}, &ApplicationPromotionRunList{})` --> `SchemeBuilder.Register(&PromotionRun{}, &PromotionRunList{})`   and it also required a `make generate` for the deepcopy to make it happy.

New stuff added:
* `PromotionRunCondition` and `PromotionRunReasonType` struct
* `PromotionRunConditionType` and `PromotionRunConditionStatus` string aliases
* 4 new consts: `PromotionRunConditionStatusTrue`, `PromotionRunConditionStatusFalse`, `PromotionRunConditionStatusUnknown`, `PromotionRunReasonErrorOccurred`

**Comment by drpaneas** [comment]
Changelog for `snapshot_types.go`

Changes:

* `ApplicationSnapshotSpec` struct rename --> `SnapshotSpec` (required to introduce changes for `SnapshotComponent` as well)
* `ApplicationSnapshotComponent` struct rename --> `SnapshotComponent`
* `SnapshotStatus` struct rename --> `SnapshotStatus
* `ApplicationSnapshot` struct rename --> `Snapshot` (required to change `SnapshotSpec` and `SnapshotStatus` as well)
* `ApplicationSnapshotList` struct rename -- `SnapshotList`
* Init `chemeBuilder.Register(&ApplicationSnapshot{}, &ApplicationSnapshotList{})` --> `	SchemeBuilder.Register(&Snapshot{}, &SnapshotList{})` (required `make generate` to keep it happy)

Nothing new was added here.

FYI: the CI is not picking up this commit. I am testing it locally with `make test` ;)

**Comment by drpaneas** [comment]
Changelog for `snapshotenvironmentbinding_types.go`

Changes:

* `SnapshotEnvironmentBindingSpec` struct rename --> `SnapshotEnvironmentBindingSpec`
* `ApplicationSnapshotEnvironmentBindingStatus` struct rename --> `SnapshotEnvironmentBindingStatus`
* `ApplicationSnapshotEnvironmentBinding` struct name --> `SnapshotEnvironmentBinding` (require change for `SnapshotEnvironmentBindingSpec` and `SnapshotEnvironmentBindingStatus`)
* `ApplicationSnapshotEnvironmentBindingList` struct name --> `SnapshotEnvironmentBindingList` (require change for `SnapshotEnvironmentBinding` as well)
* Init `	SchemeBuilder.Register(&ApplicationSnapshotEnvironmentBinding{}, &ApplicationSnapshotEnvironmentBindingList{})
` --> `	SchemeBuilder.Register(&SnapshotEnvironmentBinding{}, &SnapshotEnvironmentBindingList{})` (required `make generate` to keep it happy for the deepcopy)

**Comment by drpaneas** [comment]
Ready for review folks

@jgwest @johnmcollier

**Comment by drpaneas** [comment]
I guess it's because `//+kubebuilder:rbac:` tags are missing in general, which makes me even more curious about how the `config/rbac` or even the `config/samples` were generated in the first place.

**Comment by drpaneas** [comment]
I cannot see how these can be generated with the existing files and Makefile. The kubebuilder tags seems to be missing and the reason for missing is because they are getting generated at the controllers, not on the api side. My guess is that the individual teams who created these APIs they originally bootstraped their respective projects using `--controller` flag of operator-sdk. This created the necessary `//+kubebuilder:rbac` tags but then I assume these were removed.

Long story short I've copied over the RBAC from appstudio-shared. To me precise here's what I've done:

Same: (no need for changes)
* environment_editor_role.yaml
* environment_viewer_role.yaml

Changes: (they were only names. No any other significant change was spotted). You can observe this at https://github.com/redhat-appstudio/application-api/pull/12/commits/1a48df17aeac12346d7eae6133c4e1de5dd62b1e

* applicationpromotionrun_editor_role.yaml --> promotionrun_editor_role.yaml
* applicationpromotionrun_viewer_role.yaml --> promotionrun_viewer_role.yaml
* snapshot_editor_role.yaml --> applicationsnapshot_editor_role.yaml
* applicationsnapshot_viewer_role.yaml --> snapshot_viewer_role.yaml
* applicationsnapshotenvironmentbinding_editor_role.yaml --> snapshotenvironmentbinding_editor_role.yaml
* applicationsnapshotenvironmentbinding_viewer_role.yaml --> snapshotenvironmentbinding_viewer_role.yaml


New files: These do not exist here but they were part of appstudio-shared back in the managed-gitops repository. I've relocated them here as well just to be on the safe side. You can observe these at: https://github.com/redhat-appstudio/application-api/pull/12/commits/8896ee07f54a944742ac9666ebd8a935e86acaf8

* kustomization.yaml
* leader_election_role.yaml
* leader_election_role_binding.yaml
* role_binding.yaml
* service_account.yaml
* auth_proxy_client_clusterrole.yaml
* auth_proxy_role.yaml
* auth_proxy_role_binding.yaml
* auth_proxy_service.yaml

**Review by johnmcollier — APPROVED** [review]
Changes look good. But I want to wait til next week before merging.

**Pull request merged**
